import type { Metadata } from "next";
import { Inria_Serif, Playfair_Display } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

const inriaSerif = Inria_Serif({
  weight: ["300", "400", "700"],
  variable: "--font-inria-serif",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = (await headers()).get("X-NEXT-INTL-LOCALE") as string;
  return (
    <html lang={locale}>
      <body
        className={`${inriaSerif.variable} ${playfairDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
