import type { Metadata } from "next";
import { Inria_Serif, Playfair_Display } from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import ThemeProvider from "@/theme/theme-provider";
import Footer from "@/components/nav/Footer";
import Navbar from "@/components/nav/Navbar";

const inriaSerif = Inria_Serif({
	weight: ["300", "400", "700"],
	variable: "--font-inria-serif",
	subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-playfair-display",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<html lang={locale} suppressHydrationWarning>
			<body
				className={`${inriaSerif.variable} ${playfairDisplay.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<NextIntlClientProvider>
						<Navbar />
						{children}
						<Footer />
					</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
